### ISSUE TITLE
glibC incompatibility causing a failure in installation from conda

### ISSUE THREAD

**Issue by wanyuac** [rrwick/Trycycler#28]
Hi,

I failed to install Trycycler v0.5.3 on my ubuntu laptop due to the glibC incompatibility:

```
conda install -c conda-forge -c bioconda trycycler
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                    

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.27=0
  - feature:|@/linux-64::__glibc==2.27=0

Your installed version is: 2.27
```

I circumvented this problem using pip:

```bash
pip3 install git+https://github.com/rrwick/Trycycler.git
```

Is there a way to solve the problem of conda installation?

Thanks

------
My system configuration:
- Ubuntu 18.04.6 LTS 64 bit (kernel: Linux version 5.4.0-91-generic)
- gcc version 7.5.0
- conda 4.10.3

**Comment by nextgenusfs** [comment]
Generally the best way to avoid problems with conda is to create isolated environments for each tool, with your command above you tried to install into the `base` environment of conda -- this can cause the solver to be unable to find a solution due to conflicting dependencies from a variety of tools.  I try to install literally nothing in the `base` environment, with the exception of `mamba` which is a drop in replacement for conda that features libsolv which can solve environments much faster. So instead of installing in the base environment you can create one like:
```
conda create -n trycycler -c conda-forge -c bioconda trycycler
```

**Comment by rrwick** [comment]
Hi @wanyuac, good to hear from you!

Does @nextgenusfs's suggestion work? I just tried installing Trycycler on Ubuntu 20.04 using the [instructions on the wiki](https://github.com/rrwick/Trycycler/wiki/Installation#installing-with-conda) which use a separate environment, and it completed without error. So I at least don't think there is something fundamentally broken with the conda recipe.

I'm going to close this issue now, but please let me know if you continue to run into this problem.

Ryan
