### ISSUE TITLE
Permission Denied [13]: minimap after pip install

### ISSUE THREAD

**Issue by jacobkri** [rrwick/Trycycler#29]
Hello, 

I have installed trycycler using pip, as it would not install via conda. I have also installed minimap2 and miniasm and all requirements are in place. However, as I try to run the subsample, I keep getting the "Permission Denied [error 13]: minimap2" even with read/write permissions updated.

Is there a separate step in the installation I missed, or a part of the command line that needs to point to where minimap2 is installed? Any guidance would be appreciated.

**Comment by rrwick** [comment]
Hi @jacobkri,

Can you run minimap2 from the command line, without specifying its path? I.e. have you installed the `minimap2` executable file (with executable permission) to somewhere in your `PATH` variable? You can test this by trying to run `minimap2 --help` from the command line before you run Trycycler subsample. Trycycler just runs minimap2 as a separate command, so if it works for you outside of Trycycler, it should also work inside Trycycler.

Also, I'm curious why the conda installation didn't work. Another user had problems which were possibly due to not creating a fresh environment for Trycycler (see #28), so maybe that will help?

Let me know how you go!

Ryan

**Comment by jacobkri** [comment]
@rrwick it took time to circle back around but we finally addressed the issue. Though the dependencies to the executable files were installed, we had to manually install all dependencies and enter it into our pathway regardless of the use of tyrcycler installation via conda or pip.

**Comment by rrwick** [comment]
Thanks for the update - closing this issue now.
