### ISSUE TITLE
should I worry about the persistent indels?

### ISSUE THREAD

**Issue by fengyuchengdu** [rrwick/Trycycler#34]
after many rounds (at least 3 rounds each) of medaka, polypolish and polca polishing, I still got 14 indel errors, informed by the report from polca (shown below), 

"Substitution Errors: 0
Insertion/Deletion Errors: 14
Assembly Size: 5523242
Consensus Quality: 99.9997
Consensus QV: 55.96"

should I find other polishing tools to fix these indels, given that I don't want to add errors to the assembly?
many thanks.

**Comment by rrwick** [comment]
Literally fixing _all_ errors in a bacterial genome assembly isn't easy, mainly due to repetitive regions of the genome. As you might have already seen, I discuss this a lot in the [Polypolish paper](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1009802).

Briefly, I think that your Medaka+Polypolish+POLCA genome is probably good, and you can stop polishing there. The fact that POLCA made a few changes doesn't surprise me - it can sometimes fix things that Polypolish cannot. But if you _really_ want to get your genome as perfect as possible, I'd recommend further rounds of polishing with various tools, then manually inspecting each change and the read alignments over those changes. It's a laborious process!

Ryan
