### ISSUE TITLE
Trycycler should automatically save log to file

### ISSUE THREAD

**Issue by koolape** [rrwick/Trycycler#37]
Although the log printed on screen by Trycycler could be manually redirected to file. It would be much better if Trycycler automatically save them to a file. Those files may be useful for debug.

**Comment by rrwick** [comment]
Thanks for the suggestion. I had considered this, but I found the problem ambiguous because some Trycycler steps are per-genome and other steps are per-cluster. I.e. it wasn't obvious whether everything should go in a single log file or have one per-genome log file and then separate log files for each cluster.

In the end, I decided to be lazy and leave it up to the user, who can (as you said) manually redirect Trycycler's stderr text to a file.

For reference, if you want to put the output text in a file, you can do something like this:
```bash
TRYCYCLER COMMAND 2>> log.txt
```

Or if you want to see the output text on the screen _and_ put it in a file, then like this:
```bash
TRYCYCLER COMMAND 2>>(tee -a log.txt)
```
