### ISSUE TITLE
miniasm_and_minipolish.sh

### ISSUE THREAD

**Issue by sogriffin98** [rrwick/Trycycler#60]
Hello,

I am trying to follow the 'Assemblies' instructions on the Generating Assemblies Wiki (https://github.com/rrwick/Trycycler/wiki/Generating-assemblies).

I have ran this code: 
`python3 miniasm_and_minipolish.sh /data/ssd2/sgriffin/fallax/Genome_Assembly/Trycycler/read_subsets/sample_02.fastq "$threads" > /data/ssd2/sgriffin/fallax/Genome_Assembly/Trycycler/assemblies/assembly_02.gfa && any2fasta /data/ssd2/sgriffin/fallax/Genome_Assembly/Trycycler/assemblies/assembly_02.gfa > /data/ssd2/sgriffin/fallax/Genome_Assembly/Trycycler/assemblies/assembly_02.fasta`

and I get the following error message:
`  File "/home/sgriffin/Minipolish/miniasm_and_minipolish.sh", line 12
    overlaps=$(mktemp)".paf"
             ^
SyntaxError: invalid syntax
`

I was wondering if the issue is just me or is it a more general issue? 

Thank you :)

**Comment by rrwick** [comment]
I think the problem is that you're running `miniasm_and_minipolish.sh` through Python, but it's a Bash script not a Python script.

Change `python3 miniasm_and_minipolish.sh` to `./miniasm_and_minipolish.sh`, and it should work! Or if you copy `miniasm_and_minipolish.sh` to somewhere in your PATH variable (e.g. `/usr/local/bin` or `~/.local/bin`), then you can just run `miniasm_and_minipolish.sh` (without the leading `./`).

Ryan

**Comment by qiangqianglab** [comment]
where can i find miniasm_and_minipolish.sh?
