### ISSUE TITLE
Subsample Issue: miniasm produces 0 bp assembly

### ISSUE THREAD

**Issue by yusator** [rrwick/Trycycler#65]
I have 1 gunzipped file of nanopore long reads and I run it under the subsample command, as per the instructions of the Quick Start of the Wiki. However, since I did not define genome size (sample is unknown), it runs a quick miniasm assembly only to produce an estimated genome size of 0. AFter which, trycycler hits an error when calculating subset size. I dont know what to do
<img width="661" alt="Screenshot 2023-08-09 193259" src="https://github.com/rrwick/Trycycler/assets/136518790/0e5dfad0-4997-4f2c-9323-f6387bc3dfe3">

**Comment by rrwick** [comment]
There are really two issues here:
1. Why your reads failed to assemble with miniasm.
2. Trycycler crashing instead of giving a nice error message.

I suspect the problem behind issue 1 is your read length. I see your N50 length is 568 bp, and unless you're working with a _very_ simple genome, that's going to be insufficient for a complete assembly. So I'm sorry to say that your data is probably not suitable for Trycycler - you'll need to sequence again and get longer reads 😦

Regarding issue 2, I've just pushed a fix (ade516e) to the main branch. For your dataset, Trycycler should now quit with this message:
```
Error: genome size estimate has failed, use --genome_size to manually set a genome size
```
Thanks for bringing this to my attention!

Ryan
