### ISSUE TITLE
unicycler failed --no_correct

### ISSUE THREAD

**Issue by DingJingZhi** [rrwick/Trycycler#76]
https://github.com/rrwick/Trycycler/wiki/Guide-to-bacterial-genome-assembly#17-unicycler-hybrid-assembly
unicycler -1 short_1.fastq.gz -2 short_2.fastq.gz -s short_u.fastq.gz -l long.fastq.gz -o unicycler_assembly --threads 16 --no_correct

unicycler: error: unrecognized arguments: --no_correct
https://github.com/rrwick/Unicycler
searching, there is no no_correct.

**Comment by rrwick** [comment]
Thanks for pointing that out. The `--no_correct` option is no longer in the current version of Unicycler, so I've updated the commands in this guide (and made a few other little changes).

Also, since this guide is now [on my blog](https://rrwick.github.io/2020/10/30/guide-to-bacterial-genome-assembly.html), I've removed it from the Trycycler wiki so there aren't two separate copies.
