### ISSUE TITLE
Chloroplast genome asssembly

### ISSUE THREAD

**Issue by MehmetGoktay** [rrwick/Trycycler#8]
Hi,

I am wondering if Trycycler can be used for another kind of circular genome assembly (chloroplast) with nanopore reads?

Chloroplasts generally exist with two haplotypes in the same cell. (Same size around 150 kb with some structural variations. For example, one haplotype has an inversion around 30 kb).
 
Do you think if it is possible to assemble two haplotypes at the same time using Trycycler?

Best Regards,
Mehmet

**Comment by rrwick** [comment]
Hi Mehmet,

Trycycler should certainly be appropriate for chloroplasts. They kind of are bacteria, after all 😄 

The key here will be separating out the two haplotypes, because Trycycler should really deal with them independently. As to whether or not Trycycler can deal with the two haplotypes at the same time... I don't know but probably not.

The first obstacle to dealing with both haplotypes at the same time is that Trycycler really needs _completed_ contigs in its input assemblies. So to do both haplotypes at once, your input assemblies should each have two 150 kbp contigs: one for haplotype A one and for haplotype B. If this is the case, great! But in my experience (with metagenomes), assemblers tend to get confused when you have mixtures of similar sequences, leading to fragmented assemblies.

The other issue is in [Trycycler's clustering step](https://github.com/rrwick/Trycycler/wiki/Clustering-contigs). This clusters contigs by their _k_-mer content, and based on your description, it sounds like the two haplotypes will have very similar _k_-mers (because the differences are structural). So even if your input assemblies were good, I think Trycycler cluster will lump both haplotypes together into a single cluster, which isn't what you want. You _might_ be able to get around this by tweaking the `--distance` setting (making it very low) so that the haplotypes separate into two different clusters, but if they are extremely close this may not work.

So with all that said, I think your best bet would be phasing out the reads into haplotypes and then assembling each haplotype separately. I.e. put each read into one of two bins: haplotype A or haplotype B. Then do the entire Trycycler process independently for each. Unfortunately, I can't provide much guidance on the read phasing part - this isn't something I've done before. If there aren't existing tools for this, maybe something from the world of diploid genome phasing can help?

I hope that all makes sense! Let me know if I can clarify anything.

Ryan
