### ISSUE TITLE
Assemblers

### ISSUE THREAD

**Issue by ranitori** [rrwick/Trycycler#9]
Hi, In your wiki, under the section on assembling the subsets generated by Trycycler you mention Flye, Raven, Can etc. Is there any reason not to use Unicycler for my long-read Nanopore data? Thanks.

**Comment by rrwick** [comment]
If you're talking about a long-read-only Unicycler assembly, then yes, you could use that. However, the long-read-only approach used by Unicycler is a bit dated (e.g. it uses [minimap](https://github.com/lh3/minimap) instead of [minimap2](https://github.com/lh3/minimap2)). I would instead recommend doing [Miniasm/Minipolish](https://github.com/rrwick/Minipolish) assemblies. This is conceptually very similar to what Unicycler does but uses more up-to-date components.

If you also have short reads, then you have the option of doing a **hybrid** Unicycler assembly, which follows a very different approach. In principle, you could certainly use a hybrid Unicycler assembly as Trycycler input. But I haven't experimented much with this, and my gut feeling is that it's not a great idea. That's because hybrid Unicycler assemblies can sometimes botch repetitive regions, whereas long-read-only assemblies tend not to. So if you do have short reads, I think you're probably better off saving them for a final polish at the end of the Trycycler process. But again, I haven't tested this, so feel free to experiment!

Ryan
